version: '3.8'

services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-5000}:5000'
    volumes:
      - '.:/app'
      - /app/node_modules
    restart: always
    networks:
      - nest-backend

  db:
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    networks:
      - zmess-backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER:-zmess}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
networks:
  nest-network:
    external: true
  